<?php
    $registerUser = "INSERT INTO USERS(LOGIN_ID,PASSWORD,FIRST_NAME,LAST_NAME,ADDRESS,CITY,ZIP_CODE,COUNTRY,PHONE,EMAIL,BILLING_CITY,BILLING_ZIP_CODE, BILLING_COUNTRY,BILLING_PHONE,SHIPPING_ADDRESS,SHIPPING_CITY, SHIPPING_ZIP_CODE,SHIPPING_COUNTRY,SHIPPING_PHONE,REGISTRATION_DATE) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)";

    $authenticateUser = "SELECT * FROM USERS WHERE LOGIN_ID = %s AND PASSWORD = %s";
?>
