<?php
    $registerUser = "INSERT INTO USERS(LOGIN_ID,PASSWORD,FIRST_NAME,LAST_NAME,ADDRESS,CITY,ZIP_CODE,COUNTRY,PHONE,EMAIL,BILLING_CITY,BILLING_ZIP_CODE, BILLING_COUNTRY,BILLING_PHONE,SHIPPING_ADDRESS,SHIPPING_CITY, SHIPPING_ZIP_CODE,SHIPPING_COUNTRY,SHIPPING_PHONE,REGISTRATION_DATE) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)";

    $authenticateUser = "SELECT * FROM USERS WHERE LOGIN_ID = %s AND PASSWORD = %s";

    $insertAProduct =
    "INSERT INTO images (IMAGE, IMAGE_NAME)
        VALUES(%image, %image_name);
     INSERT INTO products (CATEGORY_ID, IMAGE_ID, VENDOR_PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, UNITS_IN_STOCK, PRODUCT_PRICE, PRODUCT_AVAILABLE, NOTES, TIMESTAMP)
        VALUES(%s,LAST_INSERT_ID(),%s,%s,%s,%s,%s,%s,%s,%s);"
?>
